// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package mailboxmessages

import (
	json "encoding/json"
	ecs "github.com/bytearena/ecs"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE3a98400DecodeGithubComBytearenaCoreGameDeathmatchMailboxmessages(in *jlexer.Lexer, out *YouHaveExitedTheMaze) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Entity":
			out.Entity = ecs.EntityID(in.Uint32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE3a98400EncodeGithubComBytearenaCoreGameDeathmatchMailboxmessages(out *jwriter.Writer, in YouHaveExitedTheMaze) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Entity\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint32(uint32(in.Entity))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v YouHaveExitedTheMaze) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE3a98400EncodeGithubComBytearenaCoreGameDeathmatchMailboxmessages(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v YouHaveExitedTheMaze) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE3a98400EncodeGithubComBytearenaCoreGameDeathmatchMailboxmessages(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *YouHaveExitedTheMaze) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE3a98400DecodeGithubComBytearenaCoreGameDeathmatchMailboxmessages(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *YouHaveExitedTheMaze) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE3a98400DecodeGithubComBytearenaCoreGameDeathmatchMailboxmessages(l, v)
}
