// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package mailboxmessages

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson79ae5888DecodeGithubComBytearenaBytearenaGameDeathmatchMailboxmessages(in *jlexer.Lexer, out *YouHaveBeenHit) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "kind":
			out.Kind = string(in.String())
		case "comingfrom":
			out.ComingFrom = float64(in.Float64())
		case "damage":
			out.Damage = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson79ae5888EncodeGithubComBytearenaBytearenaGameDeathmatchMailboxmessages(out *jwriter.Writer, in YouHaveBeenHit) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"kind\":")
	out.String(string(in.Kind))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"comingfrom\":")
	out.Float64(float64(in.ComingFrom))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"damage\":")
	out.Float64(float64(in.Damage))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v YouHaveBeenHit) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson79ae5888EncodeGithubComBytearenaBytearenaGameDeathmatchMailboxmessages(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v YouHaveBeenHit) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson79ae5888EncodeGithubComBytearenaBytearenaGameDeathmatchMailboxmessages(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *YouHaveBeenHit) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson79ae5888DecodeGithubComBytearenaBytearenaGameDeathmatchMailboxmessages(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *YouHaveBeenHit) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson79ae5888DecodeGithubComBytearenaBytearenaGameDeathmatchMailboxmessages(l, v)
}
