// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson209fd08fDecodeGithubComBytearenaBytearenaCommonTypes(in *jlexer.Lexer, out *Contestant) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Id":
			out.Id = string(in.String())
		case "Username":
			out.Username = string(in.String())
		case "AgentName":
			out.AgentName = string(in.String())
		case "AgentRegistry":
			out.AgentRegistry = string(in.String())
		case "AgentImage":
			out.AgentImage = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson209fd08fEncodeGithubComBytearenaBytearenaCommonTypes(out *jwriter.Writer, in Contestant) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Id\":")
	out.String(string(in.Id))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Username\":")
	out.String(string(in.Username))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"AgentName\":")
	out.String(string(in.AgentName))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"AgentRegistry\":")
	out.String(string(in.AgentRegistry))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"AgentImage\":")
	out.String(string(in.AgentImage))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Contestant) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson209fd08fEncodeGithubComBytearenaBytearenaCommonTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Contestant) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson209fd08fEncodeGithubComBytearenaBytearenaCommonTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Contestant) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson209fd08fDecodeGithubComBytearenaBytearenaCommonTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Contestant) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson209fd08fDecodeGithubComBytearenaBytearenaCommonTypes(l, v)
}
