// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	ecs "github.com/bytearena/ecs"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEc69e4ecDecodeGithubComBytearenaBytearenaCommonTypes(in *jlexer.Lexer, out *PhysicalBodyDescriptor) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Type":
			out.Type = string(in.String())
		case "ID":
			out.ID = ecs.EntityID(in.Uint32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEc69e4ecEncodeGithubComBytearenaBytearenaCommonTypes(out *jwriter.Writer, in PhysicalBodyDescriptor) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Type\":")
	out.String(string(in.Type))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"ID\":")
	out.Uint32(uint32(in.ID))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PhysicalBodyDescriptor) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEc69e4ecEncodeGithubComBytearenaBytearenaCommonTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PhysicalBodyDescriptor) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEc69e4ecEncodeGithubComBytearenaBytearenaCommonTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PhysicalBodyDescriptor) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEc69e4ecDecodeGithubComBytearenaBytearenaCommonTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PhysicalBodyDescriptor) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEc69e4ecDecodeGithubComBytearenaBytearenaCommonTypes(l, v)
}
